# Generated by Django 5.2.1 on 2025-05-16 11:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Astrologer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('specialization', models.CharField(max_length=255, verbose_name='Specialization')),
                ('experience', models.IntegerField(verbose_name='Experience (years)')),
                ('rating', models.FloatField(verbose_name='Rating')),
                ('reviews', models.IntegerField(verbose_name='Reviews')),
                ('price_chat', models.IntegerField(verbose_name='Chat Price (₹)')),
                ('price_voice', models.IntegerField(verbose_name='Voice Price (₹)')),
                ('price_video', models.IntegerField(verbose_name='Video Price (₹)')),
                ('chat_rate_per_min', models.IntegerField(default=10, verbose_name='Chat Rate Per Minute (₹)')),
                ('call_rate_per_min', models.IntegerField(default=20, verbose_name='Call Rate Per Minute (₹)')),
                ('photo', models.ImageField(upload_to='astrologers/', verbose_name='Photo')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Astrologer',
                'verbose_name_plural': 'Astrologers',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='categories/', verbose_name='Image')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Event Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='events/', verbose_name='Image')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='HomepageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Muhurat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time')),
                ('importance', models.CharField(max_length=100, verbose_name='Importance')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Muhurat',
                'verbose_name_plural': 'Muhurats',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Darshanam', max_length=100, verbose_name='Site Name')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Contact Email')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Maintenance Mode')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, verbose_name='Google Analytics ID')),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Compatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='User Gender')),
                ('partner_birth_date', models.DateField(verbose_name='Partner Birth Date')),
                ('partner_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Partner Gender')),
                ('compatibility_score', models.IntegerField(verbose_name='Compatibility Score')),
                ('analysis', models.TextField(verbose_name='Analysis')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_compatibility', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compatibility',
                'verbose_name_plural': 'Compatibilities',
            },
        ),
        migrations.CreateModel(
            name='Horoscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zodiac_sign', models.CharField(blank=True, max_length=50)),
                ('date_range', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('birth_time', models.TimeField(verbose_name='Birth Time')),
                ('birth_place', models.CharField(max_length=255, verbose_name='Birth Place')),
                ('analysis', models.TextField(verbose_name='Analysis')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Horoscope',
                'verbose_name_plural': 'Horoscopes',
            },
        ),
        migrations.CreateModel(
            name='Temple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Temple Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('featured_image', models.ImageField(upload_to='temples/', verbose_name='Featured Image')),
                ('gallery_images', models.JSONField(default=list, verbose_name='Gallery Images')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('google_map_url', models.URLField(blank=True, verbose_name='Google Map URL')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('categories', models.ManyToManyField(to='adminpanel.category', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Temple',
                'verbose_name_plural': 'Temples',
            },
        ),
        migrations.CreateModel(
            name='PoojaService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Service Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('duration', models.CharField(max_length=50, verbose_name='Duration')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available')),
                ('temple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.temple', verbose_name='Temple')),
            ],
            options={
                'verbose_name': 'Pooja Service',
                'verbose_name_plural': 'Pooja Services',
            },
        ),
    ]
